version: 0.2

env:
  parameter-store:
    # Requires that you have a secure string in AWS Secret Manager 
    SNYK_TOKEN: "SNYK_TOKEN"

phases:
  install:
    commands:
      - npm install -g snyk 
      - apt-get update && apt-get install jq
  build:
    commands:
      - npm install
      - npm test  # Run your unit tests, etc
      - NUM_VULNS=$(snyk test --json | jq  "[.vulnerabilities[] | select(.cvssScore >= 9)] | length"); if [ "$NUM_VULNS" != 0 ]; then exit $NUM_VULNS; fi
