version: 2.1
orbs:
  snyk: snyk/snyk@2.3.3

jobs:
  snyk-scan:
    docker:
      - image: cimg/node:16.0
    steps:
      - checkout
      - run: npm install
      - snyk/scan:
          command: monitor
          monitor-on-build: false

workflows:
  build-snyk:
    jobs:
      - snyk-scan
