name: chain_bench_scan
on: [push]
jobs:
  chain_bench_scan_example:
    runs-on: ubuntu-latest
    name: Test Job
    steps:
      - name: Chain Bench
        id: chain-bench
        uses: aquasecurity/chain-bench-action@v1.0.0
        with:
          repository-url: ${{ github.server_url }}/${{ github.repository }} # Compiles to https://github.com/aquasecurity/chain-bench-action
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # scm-platform: github #Optional parameter for dedicated SCM servers

      # Using the github action output from the scan step "chain-bench-result" (JSON so you can run rego/jq against it)
      - name: Echo
        run: echo ${{ steps.chain-bench.outputs.chain-bench-result }}
